@startuml

title primeiro testee

actor ue
participant b
participant c
participant d
database    e

ue -> b ++ : testando
group 1
    b -> e ++ : testando
    return
    c -> e ++ : testando
    return
    d -> e ++ : testando
    return
    b -> d ++ : testando
    return
end
return

@enduml