@startuml

!theme test from .

title second testee

actor ue
participant h
participant c
participant d
database    e

ue -> h ++ : testando
group 1
    h -> e ++ : testando
    return
    c -> e ++ : testando
    return
    d -> e ++ : testando
    return
    h -> d ++ : testando
    return
end
return

@enduml