@startuml

title first

actor testa
participant b
participant c
participant d
database    e

testa -> b ++ : aqui
group 1
    b -> e ++ : aqui
    return
    c -> e ++ : aqui
    return
    d -> e ++ : aqui
    return
    b -> d ++ : aqui
    return
end
return

@enduml