name: On update errors 

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*.*'

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FOLDER: 'src/adapter/query'

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: checkout
        uses: actions/checkout@v3
      - name: Render PUML to wiki
        uses: lipefebn/env@v3.3

