name: On update diagrams 

on: [push]

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WIKI_PAGE_NAME: 'Diagrams.md'
  PATH_PUML: 'docs/diagram'
  OUTPUT: 'diagrams'
  GIT_EMAIL: 'github-actions@github.com'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Render PlantUML to wiki
        uses: lipefebn/test_action@v0.3
