name: Update wiki

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Render PlantUML to wiki
        uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
        with:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
          INPUT_DIR: 'docs/diagram/puml'
          OUTPUT_DIR: 'diagrams'
